# -*- coding: utf-8 -*-
"""ASS3_053.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVOFaLTgtR5q-6HqAtrWZ3QX4ZwXz8A8
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
# %matplotlib inline

df= load_wine()

X = data.data
y = data.target

df = pd.DataFrame(X, columns=data.feature_names)
df['target'] = y

df.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X,y, test_size=0.2)

from sklearn.tree import DecisionTreeClassifier, plot_tree
# Create Decision Tree model
desc_model = DecisionTreeClassifier(criterion='gini', max_depth=2)

desc_model.fit(X_train, y_train)

y_pred = desc_model.predict(X_test)

plt.figure(figsize=(12, 8))
plot_tree(desc_model, feature_names=data.feature_names, class_names=data.target_names, filled=True)
plt.show()

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Classification Report
print("Classification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

